# Site settings
title: Li Yingwei
email1: liyw14#fudan.edu.cn
email2: prclyw#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  14ComputerScience @ Fudan University</br>
  Learning Frontend</br>
  ACM-ICPC Participant</br>
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://LiYingwei.github.io" # the base hostname & protocol for your site
twitter_username: SpaceQX
github_username:  LiYingwei
zhihu_username: yingwei-li
encoding: utf-8
# Build settings
markdown: kramdown
